### ISSUE TITLE
'npm run init' fails

### ISSUE THREAD

**Issue by rubenbakker** [brave/browser-laptop-bootstrap#12]
Can't build browser-laptop-bootstrap.
Mac OS X 10.12.2,  Xcode 8.0, node v7.3

Here are the steps performed:
1. `git clone https://github.com/brave/browser-laptop-bootstrap.git`
2. `cd browser-laptop-bootstrap/`
3. `npm install`
4. `npm run init`

`npm run init` fails with the following error:

16>From` https://chromium.googlesource.com/native_client/src/native_client
16> * [new ref]         refs/branch-heads/1025 -> branch-heads/1025
16> * [new ref]         refs/branch-heads/1271 -> branch-heads/1271
16> * [new ref]         refs/branch-heads/1271_60 -> branch-heads/1271_60
16> * [new ref]         refs/branch-heads/1312 -> branch-heads/1312
16> * [new ref]         refs/branch-heads/1364 -> branch-heads/1364
16> * [new ref]         refs/branch-heads/1750 -> branch-heads/1750
16> * [new ref]         refs/branch-heads/1985 -> branch-heads/1985
16> * [new ref]         refs/branch-heads/2009-08-14 -> branch-heads/2009-08-14
16> * [new ref]         refs/branch-heads/2009-08-14a -> branch-heads/2009-08-14a
16> * [new ref]         refs/branch-heads/2009-09-22 -> branch-heads/2009-09-22
16> * [new ref]         refs/branch-heads/2062 -> branch-heads/2062
16> * [new ref]         refs/branch-heads/2125 -> branch-heads/2125
16> * [new ref]         refs/branch-heads/2171 -> branch-heads/2171
16> * [new ref]         refs/branch-heads/2661 -> branch-heads/2661
16> * [new ref]         refs/branch-heads/648 -> branch-heads/648
16> * [new ref]         refs/branch-heads/742 -> branch-heads/742
16> * [new ref]         refs/branch-heads/782_2009_09_25 -> branch-heads/782_2009_09_25
16> * [new ref]         refs/branch-heads/835 -> branch-heads/835
16> * [new ref]         refs/branch-heads/912 -> branch-heads/912
16> * [new ref]         refs/branch-heads/963 -> branch-heads/963
16> * [new ref]         refs/branch-heads/9768 -> branch-heads/9768
16>Checked out 94bbb858ca3830bcd56fb732cc6050608787f07e to a detached HEAD. Before making any commits
16>in this repo, you should use 'git checkout <branch>' to switch to
16>an existing branch or use 'git checkout origin -b <branch>' to
16>create a new branch for your work.
Error: Command git -c core.deltaBaseCacheLimit=2g clone --progress https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git /Users/ruben/Development/browser-laptop-bootstrap/src/third_party/catapult returned non-zero exit status 128 in /Users/ruben/Development/browser-laptop-bootstrap
null
null

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "init"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! browser-laptop-bootstrap@0.13.0-pre.3 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser-laptop-bootstrap@0.13.0-pre.3 init script 'node ./scripts/sync.js --init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the browser-laptop-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/sync.js --init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs browser-laptop-bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls browser-laptop-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ruben/Development/browser-laptop-bootstrap/npm-debug.log

**Comment by bsclifton** [comment]
@rubenbakker this repo downloads the Chromium source which has a MASSIVE history.  If your connection is not reliable (connected over wifi, etc) this may be causing the issue.  Everything I see on Google Groups says to continue trying until it works. The init process should take about an hour the first time

**Comment by posix4e** [comment]
I believe we can close this issue

**Comment by bsclifton** [comment]
Per comment by @posix4e, I'll go ahead and close... but please reopen if you have more information.

If you do a search for `core.deltaBaseCacheLimit`, there are a decent number of hits for similar issues (most relating to getting the Chromium source). Although I haven't tried it, you may try to download the source minus the history

**Comment by rubenbakker** [comment]
@bsclifton Just in case somebody runs into the same issue. The issue was reproducible 100% of the time, so it wasn't related to the size of the download or my internet connection.

The problem was an outdated version of Xcode. I was using Xcode 8.0. After updating to Xcode 8.2.1 and installing the command line tools I got past the error.

**Comment by bsclifton** [comment]
@rubenbakker awesome, thanks for the update! I remember reading about folks having a similar issue after upgrading to Sierra (needing to upgrade xcode).  I had an issue with this recently (with OpenSSL libs missing) which I fixed with:
```
xcode-select --install
```

**Comment by celicoo** [comment]
@bsclifton I had the same issue and I was able to fix using the `xcode-select --install` too. Unfortunately I didn't saw this issue earlier, so it took an while until find the problem all by myself. I think it would be good to add this piece of information to the wiki, don't you think?

**Comment by bsclifton** [comment]
@celicoo thanks for the recommendation- I updated the wiki 😄  If you have a minute, please take a look (you should have access to edit also)
https://github.com/brave/browser-laptop-bootstrap/wiki
