### ISSUE TITLE
npm run init gets failed It throws "error: unknown option `unsafe-paths' "

### ISSUE THREAD

**Issue by akshay24495** [brave/browser-laptop-bootstrap#36]
error: unknown option `unsafe-paths'

**Comment by bsclifton** [comment]
@akshay24495 can you share some logs (or any more info)?

After cloning the repo, what steps did you run? What platform are you on? Do you have dependencies installed?

**Comment by akshay24495** [comment]
@bsclifton I fixed it. The git version am using dint have the option of unsafe path when i updated to latest version it worked fine.

Now I got another issue. When i run npm run create_dist in MAC x86_64. It throws an error of undefined symbol for architecture x86_64:
net::SOCKS5ClientSocketAuth

**Comment by akshay24495** [comment]
@bsclifton

**Comment by akshay24495** [comment]
@bsclifton macOS Sierra version 10.12.6

**Comment by akshay24495** [comment]
@bsclifton 
![image](https://user-images.githubusercontent.com/32266630/38363852-ddceaace-38f3-11e8-9e1f-d42237822298.png)

**Comment by akshay24495** [comment]
@bsclifton 
![screen shot 2018-04-05 at 5 09 13 pm](https://user-images.githubusercontent.com/32266630/38363950-37eb1ab0-38f4-11e8-8b76-a6f6e2049ef0.png)

**Comment by akshay24495** [comment]
@bsclifton

**Comment by bsclifton** [comment]
There hasn't been any update here (including from me; apologies)- I'm going to close this issue out. Please re-open if you're still actively trying to get this working
