### ISSUE TITLE
error on `npm run build` on Ubuntu linux

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop-bootstrap#9]
After successfully running `npm install` and `npm run init` (bit of a monster, pulls 17Gb)
I ran `npm run build` and am observing the following error:
```
npm run build
> browser-laptop-bootstrap@0.13.0-pre.3 build /home/willy/projs/git/3rd/brave/browser-laptop-bootstrap
> node ./scripts/build.js

update branding...
building node...
python /home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/build/gyp_chromium.py -D target_arch=x64 -D host_arch=x64 -D buildtype=Custom -D component=static_library -Goutput_dir=/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/out /home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/electron/vendor/node/node.gyp
Updating projects from gyp files...
compiler_version.py failed to execute: c++ -Xassembler --version -x assembler -c /dev/null
'NoneType' object has no attribute 'group'
Exception: Failed to extract compiler version for args: ['target', 'assembler']
Traceback (most recent call last):
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 496, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1266, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1145, in ProcessConditionsInDict
    variables, build_file)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1266, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1145, in ProcessConditionsInDict
    variables, build_file)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 1221, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, phase, variables, build_file)
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/tools/gyp/pylib/gyp/input.py", line 891, in ExpandVariables
    replacement = str(py_module.DoMain(parsed_contents[1:])).rstrip()
  File "/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap/src/build/compiler_version.py", line 107, in DoMain
    raise Exception("Failed to extract compiler version for args: %s" % args)
Exception: Failed to extract compiler version for args: ['target', 'assembler']

null
null
```

n.b. I'm keeping this issue as a log more than a request for help -- I know you guys are busy.

I expect I'll figure this out, will update as I work through various issues.

**Comment by posix4e** [comment]
@willy-b  can you install build-essentials?

**Comment by willy-b** [comment]
@posix4e build-essential is already at latest version

**Comment by posix4e** [comment]
@willy-b  what does c++ --version say?

**Comment by willy-b** [comment]
```
> c++ --version
/usr/bin/g++ -g --version
g++.orig (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

**Comment by posix4e** [comment]
What happens when you run c++ -Xassembler --version -x assembler

**Comment by posix4e** [comment]
I'm trying to figure out what's wrong. Yea re-running init sounds good

**Comment by posix4e** [comment]
You did

npm install && npm run init && npm run build?

**Comment by willy-b** [comment]
yes, that sequence exactly.
`npm run init` took a long time but finished without errors this run.
since it had failed earlier with errors in same directory previously and there is not a `npm run clean` command I have restarted this AM with a fresh clone, re-running `npm install` and `npm run init`.

**Comment by willy-b** [comment]
I think it failed to give paths to g++ because `realpath` is missing on my machine
same issue as highlighted here: http://chromium-bugs.chromium.narkive.com/aim6QvvK/issue-415441-in-chromium-chrome-on-cros-workflow-gyp-chromium-failure-for-arm-generic-failed-to

**Comment by willy-b** [comment]
`npm run build` still fails after a completely fresh `git clone`, `npm install`, and `npm run init` (no errors on those steps).

**Comment by willy-b** [comment]
The error before:
```
compiler_version.py failed to execute: c++ -Xassembler --version -x assembler -c /dev/null
[...]
Exception: Failed to extract compiler version for args: ['target', 'assembler']
```
was caused by compiler_version.py not handling multiple lines of output from `g++` properly (using a single line regex on multiple lines of output). 

fixed that locally -- I'll submit a consolidated PR for suggested build fixes after I get everything else working.

**Comment by willy-b** [comment]
now I'm seeing a lot of errors relating to missing/undefined variables in `src/electron/vendor/node/node.gyp`.

these errors come up only one at a time as you fix them, but here's a list obtained by patching each one with `false` or `''` depending on the type inferred from the error message:
```
gyp: name 'node_enable_d8' is not defined while evaluating condition 'node_enable_d8=="true"' in src/electron/vendor/node/node.gyp
gyp: name 'node_use_chromium_v8' is not defined while evaluating condition 'node_use_chromium_v8=="true"' in src/electron/vendor/node/node.gyp
gyp: name 'node_tag' is not defined while evaluating condition 'node_tag!=""' in src/electron/vendor/node/node.gyp
gyp: name 'node_release_urlbase' is not defined while evaluating condition 'node_release_urlbase!=""' in src/electron/vendor/node/node.gyp
gyp: name 'icu_small' is not defined while evaluating condition 'icu_small=="true"' in src/electron/vendor/node/node.gyp
gyp: name 'v8_inspector' is not defined while evaluating condition 'v8_inspector=="true"' in src/electron/vendor/node/node.gyp
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in src/electron/vendor/node/node.gyp
gyp: Undefined variable OPENSSL_PRODUCT in src/electron/vendor/node/node.gyp
gyp: name 'v8_postmortem_support' is not defined while evaluating condition 'node_use_bundled_v8=="true" and v8_postmortem_support=="true"' in src/electron/vendor/node/node.gyp
gyp: Undefined variable V8_BASE in src/electron/vendor/node/node.gyp
```

**Comment by willy-b** [comment]
I had to restart `npm run build` a few times for various reasons but everything works now. Will submit PR for `compiler_version.py` change after cleanup.

**Comment by willy-b** [comment]
Hmm. `compiler_version.py` comes from upstream Chromium native_client repo. 
See original file and problematic lines at: https://chromium.googlesource.com/native_client/src/native_client.git/+/cf2f849333d73dc394c4576a60fbc641a4b43c0f/build/compiler_version.py#90 .

`compiler_version.py` has already been removed upstream so should we just update to more recent rev to inherit their fix or should we patch here to ensure build works on Linux?

**Comment by posix4e** [comment]
patch here for now

**Comment by willy-b** [comment]
what's the preferred way to apply a patch to a third party repo here?

the path in question is in a sub-repo: `src/native_client` with remote `https://chromium.googlesource.com/native_client/src/native_client.git`.

so we need to setup a script that patches that as part of the build process akin to what is being done with `src/electron/script/apply-patches.py`, right? (e.g. how  `src/electron/patches/master_patch.diff` modifies `src/electron/chromium_src`)

my first pass thinking is that since this patch is outside of Muon (`src/electron`) we would add another `apply-patches` script at the top level. what do you think?

**Comment by willy-b** [comment]
nevermind, I see that putting the patch with the other patches inside Muon's master patch file works fine because Muon's `apply_patches.py` is executed as part of `browser-laptop-bootstrap`'s `npm run sync` script.
So I'll submit the PR in Muon then against `patches/master_patch.patch`.

**Comment by bsclifton** [comment]
@willy-b to create patches, you can run `npm run update_patches` after you've made the change :smile:

**Comment by willy-b** [comment]
this is outdated. the issue has been resolved.
